name: Fontbakery QA

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fontbakery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Fontbakery
        run: |
          pip install fontbakery[googlefonts]

      - name: Run Fontbakery
        run: |
          fontbakery check-googlefonts fonts/ttf/*.ttf --ghmarkdown fontbakery-report.md

      - name: Upload Fontbakery Report
        uses: actions/upload-artifact@v4
        with:
          name: fontbakery-report
          path: fontbakery-report.md
